version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    volumes:
      - ./static:/app/static
    depends_on:
      - flask_app1
      - flask_app2
      - flask_app3
      - flask_app4
    networks:
      - app_network

  flask_app1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
      - GOOGLE_CLIENT_ID=507995986306-qcdrhrrt3d71la4pkrf7lt1b2tvuusqm.apps.googleusercontent.com
      - GROQ_CLIENT_ID=your-groq-client-id
      - GROQ_CLIENT_SECRET=your-groq-client-secret
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/*/__pycache__
      - /app/*/*/__pycache__
    networks:
      - app_network

  flask_app2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
      - GOOGLE_CLIENT_ID=your-google-client-id
      - GROQ_CLIENT_ID=your-groq-client-id
      - GROQ_CLIENT_SECRET=your-groq-client-secret
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/*/__pycache__
      - /app/*/*/__pycache__
    networks:
      - app_network

  flask_app3:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
      - GOOGLE_CLIENT_ID=your-google-client-id
      - GROQ_CLIENT_ID=your-groq-client-id
      - GROQ_CLIENT_SECRET=your-groq-client-secret
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/*/__pycache__
      - /app/*/*/__pycache__
    networks:
      - app_network

  flask_app4:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
      - GOOGLE_CLIENT_ID=your-google-client-id
      - GROQ_CLIENT_ID=your-groq-client-id
      - GROQ_CLIENT_SECRET=your-groq-client-secret
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/*/__pycache__
      - /app/*/*/__pycache__
    networks:
      - app_network

networks:
  app_network:
    driver: bridge 